### ISSUE TITLE
not detected

### ISSUE THREAD

**Issue by Vabis1010** [iMicknl/ha-nest-protect#11]
### The problem

don't know if it schould be like this but my occupancy and smoke detection sensors gif state not detected. When i see the example pic in the github it schould give other states or am i wrong?
Happy with the program because now i can integreate my nestprotects in the automations.

Ton

### What version of this integration (ha-nest-protect) has the issue?

0.1.1

### What version of Home Assistant Core has the issue?

supervissor

### Device / Model

nest protect battery

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Could you maybe add a picture of what you see to start with? From there we could investigate and perhaps turn on more debug logging.

**Comment by Vabis1010** [comment]
![Screenshot_20220128-134850_Chrome](https://user-images.githubusercontent.com/86514586/151559460-db36485e-ec7e-4116-8d3e-e9f2af95cf06.jpg)

**Comment by Vabis1010** [comment]
I hope ik help YouTube out with thuis.

**Comment by Vabis1010** [comment]
![Screenshot_20220128-134850_Chrome](https://user-images.githubusercontent.com/86514586/151559733-79876879-17c0-4b22-8125-79b18df30f88.jpg)

**Comment by iMicknl** [comment]
Thanks, this clarifies the situation. Try changing the Home Assistant language for your user to English, and compare the screenshots again. 😉

In Dutch 'Niet gedetecteerd' means the same as 'Clear' in English. There is no smoke or occupancy detected, thus you should be happy! 😄

**Comment by Vabis1010** [comment]
THanks for the update. At leest nog iets know my nest protects are running oke
and i can use them in automations. Is it true Thatcher the occupancy sensor online works on wired protects and not on battery operTed one

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by iMicknl** [comment]
It doesn't make (a lot of) sense to use them in your integrations yet, since the state of your sensors will only update when you start Home Assistant (or reload the integration). However, these live updates will come in a future version, so at least you are ready.

If I am correct, occupancy only works on wired protects, thus I am not sure why they show up for you. We can investigate that later, when the live updates are here.

See https://github.com/iMicknl/ha-nest-protect#known-limitations-and-issues
