### ISSUE TITLE
How do you trigger the smoke sensor status

### ISSUE THREAD

**Issue by benotje** [iMicknl/ha-nest-protect#23]
### The problem

 Real-time updates smoke sensor is Nest Protect (Kitchen) Smoke Status "Not Detected"    
I hope that can be solved first then we can show the status on the dashboard
that would be really cool

![image](https://user-images.githubusercontent.com/25820512/156233845-66cffa34-2e73-4953-bb08-442a12ff4377.png)

### What version of this integration (ha-nest-protect) has the issue?

0.1.0

### What version of Home Assistant Core has the issue?

core-2022.2.9

### Device / Model

nest protect Topaz-2.7 smoke alarm

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>
..

### Additional information

..

**Comment by iMicknl** [comment]
@benotje thanks for reporting. Just checking; are you aware that real-time updates are not possible yet? (for none of the entities). This is currently stated in the README.

In order to see if your smoke status works, you could try to trigger the smoke alarm and than reload the integration in Home Assistant. (press the dots next to the integration and pick 'reload'). This will show the last available status.
