### ISSUE TITLE
Support for battery health for wired protects

### ISSUE THREAD

**Issue by RealGandy** [iMicknl/ha-nest-protect#27]
### Description

Hi

The old version also supported a status for the backup battery for wired nest protects. Is this something you can look at adding if its available?
Thanks

**Comment by iMicknl** [comment]
This should be possible, if the 'old version' has it as well. Did you use 'badnest' or 'homebridge-nest' before?

I have a wired nest protect as well, and I have a battery sensor present by the way. It is a binary sensor (Normal / Empty). 

<img width="252" alt="image" src="https://user-images.githubusercontent.com/1424596/157001190-605315bb-3c64-4c21-9b71-20e249312c31.png">

**Comment by RealGandy** [comment]
Ah, OK.

I now see that there are a whole host of other entities available that didn't immediately show up in the default views. 

I'm happy for this request to be closed as the data is already available.

Does this just grab updates from API, so if a device does identify smoke HA won't show this until the next request to the API? Or does it also register for webhook pushes when certain events occur?


Thanks

**Comment by iMicknl** [comment]
Indeed, this integration uses the Home Assistant entity categories to divide the entities by type. In your default lovelace interface, you will only see the main entities by default.

The integration subscribes to new events, thus these should be almost instant. Since you have a wired protect, you can check this with the occupancy. These updates should be in in 3-5 seconds.
