### ISSUE TITLE
Beta v4 instructions need to be customized for MacOS

### ISSUE THREAD

**Issue by BlackRockCity** [iMicknl/ha-nest-protect#274]
### Description

I dont see the iframeRPC on a mac. A better tutorial is needed for macos users.

**Comment by BlackRockCity** [comment]
Update: I got it working. There were two areas of struggle: 1) the configuration form contains two methods with no explanation of which to use (sign in with google account and (field test). When the first method didn't work I tried the 2nd method only to have to go back to the first. 2) the configuration form has no label... its not crystal clear that the issueToken goes in the first field and that the cookie goes in the second field. I assumed this correctly, but it would be nice if they were labeled. 

Regarding mac users: For some reason filtering for IssueToken didn't show anything at all... then I open my macbook a day later after leaving the page open and it finally does show two iFramerpc entrities. Letting it sit, seemed to make this data show up. Why did it take so long?

The instructions say to first filter for issueToken and then to filter for oauth2/iframe but on a mac these show the exact same data, so its a superfluous instruction that can be eliminated. Coupled with no data showing at all initially only to appear hours late, it added to the confusion.

**Comment by iMicknl** [comment]
Thanks @BlackRockCity. I hope to have some more time for this, so thanks for your clear feedback.

Regarding your first question; in HACS you can select "Show beta versions" in the dialog, to install the beta version. Hopefully this hassle with needing a beta version will be gone soon. The fields should be labeled now, but I have seen issues with no labels with other people that had an older version. If you install the latest beta version (manually) this should work.

**Comment by jnxxx** [comment]
I have now tried to update the instructions on how to retrieve issue_token and cookies.
It is mainly incorporation of #272, and a bit of formatting and checking menu names etc.

Furthermore I added a description to the account selection step.
I am not really sure myself, but seems to be production and test. So, basically saying to use the default one.
The link in the second step is fine (points to beta branch though).

I do not have a Mac available, so I cannot check the findings reported there.
The menu layout could be different and searching in dev. tools, but the core browser functionality should hopefully be the same.

Regarding issueToken and oauth2/iframe (last entry) finding the same request: I do see this, but only if there was a session already. If clearing cookies or using Incognito it is two different requests. Therefore I kept this.
The issueToken request gets the same cookies as input/request, but updates one of them which can be found under response. Rather than user having to merge request and response cookies, oauth2/iframe (last entry) finds the subsequent request where most recent cookies can be found under request cookies.
Based on my own experience, I would just recommend using Incognito now there is a description on how to work around the third-party cookie issue.

**Comment by jnxxx** [comment]
I do not have a Mac, so I cannot try it out.

But in my experience (on Windows and ChromeOS), if a user is already logged in, then the two searches will find the exact same request in dev. tools.
With cleaned cookies or Incognito, it finds two different requests.
issueToken do have many (if not all) of the same cookies, but it updates one in response.

My experience when not properly cleaned, is that it led to reduced session lifetime.

If searching in dev. tools works differently, one possibility might be to search for "accounts.google.com" (hostname). It seems the second-last will be the issueToken, and last one the cookies.

**Comment by BlackRockCity** [comment]
I was able to enable the beta downloads by going to HACS and clicking the nest card then choosing redownload from the ... menu and then activating beta versions.

the fields were now labeled. 4.0b4

I had a better time doing this under Microsoft Edge Browser for MacOS. 

Opened a New private browsing window. 

loaded home.nest.com

logged in. 

found the network tab and checked preserve log
 
signed out.

… > more tools > application > storage tab (on the left) > clear site data

logged in again.

followed these instructions to get the issueToken request url and oauth/iframe and request header cookie and the instructions worked:

https://community.home-assistant.io/t/integrating-nest-protect-smoke-alarms/603253

now i will see how long the cookie lasts
