### ISSUE TITLE
Change entities name

### ISSUE THREAD

**Issue by Vabis1010** [iMicknl/ha-nest-protect#45]
### Description

As in have my homeassistant in dutch i have the following problem. On my lovelace when i look on for example nestprotect smoke it states 'niet beschikbaar. Not availible. Is rather confucianisme. Is there a wat to adjust?
Woud be a gratis improvement.
Thans on advance Ton

**Comment by iMicknl** [comment]
<img width="484" alt="Screen Shot 2022-03-13 at 01 14 41" src="https://user-images.githubusercontent.com/1424596/158039469-86359f2a-1c26-4fd7-98eb-f323e2d38e15.png">

Are you sure it says 'Niet beschikbaar'? Mine says 'Niet gedetecteerd'. We cannot change this, since this is the translation of Home Assistant, however if it says 'Niet beschikbaar' we have another problem.

Could you include your diagnostics file and turn on debug logging? (see README).

**Comment by iMicknl** [comment]
Geen probleem! Voor automations kun je 'on' en 'off' gebruiken, omdat het een binary sensor is.

**Comment by Vabis1010** [comment]
Oke bedankt voor de info.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
