### ISSUE TITLE
RFE: add support for direct installation via HA add-on

### ISSUE THREAD

**Issue by pcmoore** [iMicknl/ha-nest-protect#86]
### Description

First off, thank you for your work on this, I and many others really appreciate what you've done here - thank you!

If you have the time, and inclination, it would be very nice if you could add support for installing this as a proper HA add-on.  I'm sure you aware of the docs already, but just in case here is a link to the HA docs on building add-ons:

* https://developers.home-assistant.io/docs/add-ons/tutorial

Being able to manage this add-on directly via the native HA tools would be a very nice addition.

**Comment by iMicknl** [comment]
Thanks for your suggestion, @pcmoore! This is a component and not an add-on, thus this is not applicable. In the long term the plan would be to add this integration to core; however there are a lot of bugfixes and code quality changes that need to be applied in order to make it ready for core.


See the following explanation about [the difference between an add on and a component](https://www.reddit.com/r/homeassistant/comments/711u7f/what_is_the_difference_between_an_add_on_and_a/).
